export type CatalogTone = "ready" | "review" | "locked";

export type FixPlaybook = {
  key: string;
  phase: string;
  module: string;
  title: string;
  shortTitle: string;
  route: string;
  scanFinding: string;
  whatToFix: string[];
  doFirst: string[];
  setupOptions: string[];
  proof: string[];
  unlocks: string[];
  training: string;
};

export type FixModule = {
  phase: string;
  module: string;
  summary: string;
  keys: string[];
};

export type AccountCatalogItem = {
  name: string;
  group: string;
  type: string;
  requirements: string[];
  recommended: string[];
  fixKeys: string[];
  timing: string;
  why: string;
  applyHref: string;
  gradient: string;
};

export const canonicalFixOrder = ["phones", "address", "website", "email", "llc", "ein", "bank", "bank-rating", "criteria", "net30"];

export const fixModules: FixModule[] = [
  {
    phase: "Phase 1",
    module: "Business Identity",
    summary: "Phone, 411, address, website, and domain email signals vendors compare first.",
    keys: ["phones", "address", "website", "email"],
  },
  {
    phase: "Phase 2",
    module: "Legal Setup",
    summary: "Entity type, legal name, state records, EIN, and IRS proof alignment.",
    keys: ["llc", "ein"],
  },
  {
    phase: "Phase 3",
    module: "Banking Foundation",
    summary: "Business bank account setup, profile consistency, and bank-rating habits.",
    keys: ["bank", "bank-rating"],
  },
  {
    phase: "Phase 4",
    module: "Approval Readiness",
    summary: "Business credit criteria, bureau/profile checks, and application timing.",
    keys: ["criteria"],
  },
  {
    phase: "Phase 5",
    module: "Starter Vendor Credit",
    summary: "Net 30 readiness and vendor category selection before applications.",
    keys: ["net30"],
  },
];

export const fixPlaybooks: Record<string, FixPlaybook> = {
  phones: {
    key: "phones",
    phase: "Phase 1",
    module: "Business Identity",
    title: "Phone & 411 Fix",
    shortTitle: "Phone signal",
    route: "/phones-and-411/",
    scanFinding: "The business phone signal must look like a real business line and be consistent across public records before account applications.",
    whatToFix: ["Dedicated business phone number", "Caller ID/business name match", "Public 411 or business directory listing", "Same number on website, bank, and applications"],
    doFirst: ["Pick the primary business number.", "Set the caller ID to the public business name.", "Add or verify a public business listing.", "Update every application/profile with the same number."],
    setupOptions: ["TurnCom360 Business Phone Setup", "Grasshopper Business Line", "Business VoIP Setup Review", "Caller ID / Business Name Match", "411 Listing Support", "Done-For-You Phone Signal Fix"],
    proof: ["Phone account screenshot", "Caller ID/business name screenshot", "Directory/411 listing screenshot", "Website contact page with matching phone"],
    unlocks: ["Starter Net 30 vendors", "Fleet/fuel account readiness", "Higher-trust vendor verification", "Cleaner business identity review"],
    training: "Compact lesson: why phone type, caller ID, and directory consistency matter before vendor applications.",
  },
  address: {
    key: "address",
    phase: "Phase 1",
    module: "Business Identity",
    title: "Business Address Fix",
    shortTitle: "Address consistency",
    route: "/business-address/",
    scanFinding: "The business address should match across website, public records, bank records, and account applications.",
    whatToFix: ["One exact address format", "Commercial/business-appropriate address use", "Website and directory consistency", "Bank and vendor application consistency"],
    doFirst: ["Choose the exact address format.", "Update the website/contact profile.", "Match state, bank, and vendor profiles.", "Save proof before applying."],
    setupOptions: ["Business Address Review", "Address Consistency Cleanup", "Business Address Setup Guidance", "Records Match Review", "Done-For-You Address Cleanup"],
    proof: ["Website contact screenshot", "State/business profile record", "Bank profile or application screenshot", "Directory listing screenshot"],
    unlocks: ["Grainger-style vendor reviews", "Home improvement/project accounts", "Business bank and bureau profile consistency"],
    training: "Compact lesson: why mailbox, home, and inconsistent address signals can slow underwriting.",
  },
  website: {
    key: "website",
    phase: "Phase 1",
    module: "Business Identity",
    title: "Website & Domain Fix",
    shortTitle: "Website/domain",
    route: "/website-domain-email/",
    scanFinding: "The business needs a credible website/domain signal that matches the company identity.",
    whatToFix: ["Active business domain", "Website with matching name, address, and phone", "Contact page", "Professional public presence"],
    doFirst: ["Confirm the domain is active.", "Add business identity details to the site.", "Make the contact page match records.", "Keep the site live before applications."],
    setupOptions: ["Website Setup", "Website Credibility Review", "Business Profile Cleanup", "Done-For-You Web Presence Setup"],
    proof: ["Homepage screenshot", "Contact page screenshot", "Domain/DNS screenshot", "Business profile screenshot"],
    unlocks: ["Quill and Staples-style reviews", "Technology vendors", "Credit card readiness checks"],
    training: "Compact lesson: how a real web presence supports automated verification.",
  },
  email: {
    key: "email",
    phase: "Phase 1",
    module: "Business Identity",
    title: "Domain Email Fix",
    shortTitle: "Domain email",
    route: "/website-domain-email/",
    scanFinding: "The primary contact email should use the business domain instead of a free mailbox.",
    whatToFix: ["Domain email address", "Email shown on website/contact profiles", "Application contact email consistency", "Free email kept only as backup"],
    doFirst: ["Create a domain email account.", "Put it on the website contact page.", "Update vendor/bank profiles.", "Save proof before applying."],
    setupOptions: ["Domain Email Setup", "Google Workspace Setup", "Microsoft 365 Business Email Setup", "Business Profile Cleanup", "Done-For-You Web Presence Setup"],
    proof: ["Domain email inbox screenshot", "Website contact page screenshot", "Updated business profile screenshot"],
    unlocks: ["Website/domain-dependent vendors", "Card path review", "Professional identity confidence"],
    training: "Compact lesson: why domain email is different from simply having any email address.",
  },
  llc: {
    key: "llc",
    phase: "Phase 2",
    module: "Legal Setup",
    title: "Entity Type & State Record Review",
    shortTitle: "Legal entity",
    route: "/llc-vs-corporation/",
    scanFinding: "Legal setup should match the name, entity type, and state record used everywhere else.",
    whatToFix: ["Entity type review", "State filing check", "Legal/public name match", "Ownership/contact consistency"],
    doFirst: ["Confirm the legal entity type.", "Check the state record.", "Match the public business name.", "Save the state record proof."],
    setupOptions: ["Entity Type Review", "State Filing Check", "Business Name Match Review", "Entity Setup Guidance"],
    proof: ["State entity record", "Articles/formation document", "Business name match screenshot"],
    unlocks: ["EIN alignment", "Business bank setup", "Most vendor/category applications"],
    training: "Compact lesson: entity consistency before EIN, bank, and vendor records.",
  },
  ein: {
    key: "ein",
    phase: "Phase 2",
    module: "Legal Setup",
    title: "EIN Identity Match",
    shortTitle: "EIN",
    route: "/ein/",
    scanFinding: "The EIN should connect to the same legal business identity used on records and applications.",
    whatToFix: ["EIN confirmation", "IRS letter saved", "Legal name match", "Bank/vendor identity match"],
    doFirst: ["Locate or request the EIN letter.", "Compare legal name formatting.", "Save proof.", "Use the same identity on bank/vendor profiles."],
    setupOptions: ["EIN Verification Checklist", "IRS Letter Proof Save", "EIN Identity Match Review", "EIN Setup Guidance"],
    proof: ["IRS EIN letter", "State record", "Bank profile using matching name"],
    unlocks: ["Starter Net 30 vendors", "Business bank profile", "Credit bureau/profile tools"],
    training: "Compact lesson: why EIN proof matters before applications.",
  },
  bank: {
    key: "bank",
    phase: "Phase 3",
    module: "Banking Foundation",
    title: "Business Bank Account Fix",
    shortTitle: "Bank account",
    route: "/bank-account/",
    scanFinding: "A business bank account should be open and match the same company identity used publicly.",
    whatToFix: ["Business checking account", "Bank profile name/address match", "Operating deposits", "Account proof saved"],
    doFirst: ["Open or confirm the business checking account.", "Match the company identity.", "Use it consistently.", "Save proof before card/funding applications."],
    setupOptions: ["Business Bank Account Checklist", "Bank Profile Match Review", "Banking Setup Guidance", "Bank Account Proof Save"],
    proof: ["Bank welcome/profile screen", "Business bank statement", "Profile details showing matching business identity"],
    unlocks: ["Bank-rating work", "Credit card readiness", "Funding path review"],
    training: "Compact lesson: banking as a stability signal, not just a place for deposits.",
  },
  "bank-rating": {
    key: "bank-rating",
    phase: "Phase 3",
    module: "Banking Foundation",
    title: "Bank Rating Fix",
    shortTitle: "Bank rating",
    route: "/bank-rating/",
    scanFinding: "The bank relationship and average balance signal should be stronger before higher-value account applications.",
    whatToFix: ["Average balance target", "90-day banking pattern", "Statement proof", "Application timing"],
    doFirst: ["Pick a realistic average-balance target.", "Track balances over time.", "Avoid applying during weak balance periods.", "Save statements/proof."],
    setupOptions: ["Bank Profile Match Review", "Banking Setup Guidance", "Bank Rating Review", "Bank Account Proof Save"],
    proof: ["Recent business bank statement", "Balance tracker", "Application timing note"],
    unlocks: ["Capital One Spark", "Chase Ink", "American Express Business", "Bank funding conversations"],
    training: "Compact lesson: how bank activity affects readiness without guaranteeing funding.",
  },
  criteria: {
    key: "criteria",
    phase: "Phase 4",
    module: "Approval Readiness",
    title: "12-Point Business Credit Criteria",
    shortTitle: "Readiness criteria",
    route: "/business-credit-criteria/",
    scanFinding: "The business should pass the core identity, banking, profile, and timing checks before broader applications.",
    whatToFix: ["Identity consistency", "Bureau/profile checks", "Business website/email", "Bank and vendor history", "Application timing"],
    doFirst: ["Review all readiness criteria.", "Fix mismatched records first.", "Delay applications until blockers are cleared.", "Save proof for every completed item."],
    setupOptions: ["Business Credit Criteria Review", "Profile Cleanup Review", "Application Timing Review", "Done-For-You Readiness Review"],
    proof: ["Criteria checklist", "Profile screenshots", "Saved fix proof", "Application readiness notes"],
    unlocks: ["Traditional business cards", "Corporate/no-PG review", "Funding readiness paths"],
    training: "Compact lesson: how readiness criteria protects against wasted applications.",
  },
  net30: {
    key: "net30",
    phase: "Phase 5",
    module: "Starter Vendor Credit",
    title: "Net 30 Vendor Readiness",
    shortTitle: "Net 30",
    route: "/about-net-30/",
    scanFinding: "Starter vendors should be selected after identity, EIN, address, website/email, and bank signals are ready enough for review.",
    whatToFix: ["Vendor category selection", "Requirements check", "Application timing", "Reporting expectations"],
    doFirst: ["Choose a vendor category that matches the business.", "Check required signals.", "Apply only when identity records match.", "Track payment history and reporting."],
    setupOptions: ["Starter Vendor Account Review", "Vendor Category Selection", "Net 30 Timing Guidance", "Application Prep Review"],
    proof: ["Vendor approval/terms screenshot", "Invoice/payment proof", "Reporting or account status screenshot"],
    unlocks: ["Starter Net 30 vendors", "Retail/wholesale vendors", "Fleet and fuel cards", "Credit card readiness"],
    training: "Compact lesson: use vendor accounts to build clean payment history, not random applications.",
  },
};

export const accountCatalog: AccountCatalogItem[] = [
  ...[
    "Crown Office Supplies",
    "Uline",
    "Quill",
    "Grainger",
    "Nav Prime / Business Boost",
    "eCredable Business",
    "CreditStrong Business",
    "NAMYNOT",
    "Creative Analytics",
    "Branded Apparel Club",
  ].map((name, index) => ({
    name,
    group: "Starter Net 30 vendors",
    type: index < 4 ? "Starter vendor account" : "Credit profile / builder tool",
    requirements: ["Legal entity", "EIN", "Phone/address consistency", "Business bank account"],
    recommended: ["Website", "Domain email", "90+ days in records"],
    fixKeys: index < 2 ? ["ein", "phones", "address"] : ["ein", "phones", "address", "website"],
    timing: "Use after the foundation is clean enough for starter vendor review.",
    why: "Starter path for building controlled payment history when the profile is consistent.",
    applyHref: "/starter-net-30-vendors/",
    gradient: index % 2 ? "linear-gradient(135deg,#0E1A2B,#2563EB)" : "linear-gradient(135deg,#0E1A2B,#15803D)",
  })),
  ...[
    "Coast to Coast Office Supply",
    "Nine to Five Essentials",
    "GoodNeon",
    "Office Garner",
    "The CEO Creative",
    "Wise Business Plans",
    "JJ Gold International",
    "Summa Office Supplies",
    "Maverick Office Supplies",
    "Ohana Office Products",
  ].map((name, index) => ({
    name,
    group: "Office supply vendors",
    type: "Office / operating vendor",
    requirements: ["EIN", "Business address", "Phone signal", "Website or domain email"],
    recommended: ["Bank account", "Starter vendor history"],
    fixKeys: ["ein", "address", "phones", index > 4 ? "website" : "email"],
    timing: "Use for routine purchasing history after identity records line up.",
    why: "Office vendors should support real business operations and clean payment behavior.",
    applyHref: "/office-and-cleaning/",
    gradient: index % 2 ? "linear-gradient(135deg,#1E3A8A,#38BDF8)" : "linear-gradient(135deg,#111827,#64748B)",
  })),
  ...[
    "HD Supply",
    "Home Depot Pro / SupplyWorks",
    "Strategic Network Solutions",
    "Gempler's",
    "Home Depot Commercial Account",
    "Lowe's Pro",
    "United Rentals",
  ].map((name, index) => ({
    name,
    group: "Industrial/building vendors",
    type: "Building / industrial account",
    requirements: ["EIN", "Address consistency", "Business bank account", "Website"],
    recommended: ["90+ days", "Vendor history", "Project/business use"],
    fixKeys: ["ein", "address", "bank", "website"],
    timing: "Use when the business activity supports project, trade, or operational purchases.",
    why: "Industrial accounts often expect a more complete operating profile.",
    applyHref: "/building-and-industrial/",
    gradient: index % 2 ? "linear-gradient(135deg,#713F12,#B45309)" : "linear-gradient(135deg,#0F172A,#334155)",
  })),
  ...[
    "Amazon Business Pay by Invoice",
    "Staples Business",
    "Office Depot Business",
    "Wayfair Professional",
    "Costco Business",
    "Sam's Club Business",
    "BJ's Business",
    "Shirtsy",
    "Business T-Shirt Club",
    "Red Spectrum",
    "Shogun Roasting",
  ].map((name, index) => ({
    name,
    group: "Retail/wholesale vendors",
    type: "Retail / wholesale account",
    requirements: ["EIN", "Phone", "Address", "Website"],
    recommended: ["Bank account", "Domain email", "Operational need"],
    fixKeys: ["ein", "phones", "address", "website"],
    timing: "Use after the core identity signals are consistent and the account fits the business.",
    why: "Retail and wholesale accounts should support inventory or operating needs, not random applications.",
    applyHref: "/retail-and-wholesale/",
    gradient: index % 2 ? "linear-gradient(135deg,#172554,#2563EB)" : "linear-gradient(135deg,#0E1A2B,#0F766E)",
  })),
  ...[
    "BP Business Solutions",
    "Shell Fleet",
    "WEX",
    "Fleet One",
    "Universal Premium FleetCard",
    "Chevron Texaco Business Card",
    "Valero Fleet Plus",
    "76 Business Fleet Card",
    "ARCO Business Solutions",
    "Ford Pro",
  ].map((name, index) => ({
    name,
    group: "Fleet and fuel cards",
    type: "Fleet / fuel account",
    requirements: ["Entity", "EIN", "Phone", "Address", "Bank account"],
    recommended: ["90+ days", "Vehicle/business use", "Website"],
    fixKeys: ["llc", "ein", "phones", "address", "bank"],
    timing: "Use when the company has real driving, fleet, delivery, or service vehicle needs.",
    why: "Fleet accounts work best when the business use case is clear and identity records match.",
    applyHref: "/gas-fleet-and-auto/",
    gradient: index % 2 ? "linear-gradient(135deg,#7F1D1D,#DC2626)" : "linear-gradient(135deg,#111827,#F59E0B)",
  })),
  ...[
    "Apple Business",
    "Dell Business",
    "Best Buy Business",
    "Lenovo Pro",
    "NeweggBusiness",
  ].map((name, index) => ({
    name,
    group: "Technology vendors",
    type: "Technology / equipment account",
    requirements: ["EIN", "Website", "Domain email", "Readiness criteria"],
    recommended: ["Bank account", "Vendor history", "Business use"],
    fixKeys: ["ein", "website", "email", "criteria"],
    timing: "Use when website/email and business purpose are credible.",
    why: "Technology vendors often expect a cleaner business presence and stronger verification signals.",
    applyHref: "/high-tech-auto-vendors/",
    gradient: index % 2 ? "linear-gradient(135deg,#312E81,#7C3AED)" : "linear-gradient(135deg,#0F172A,#2563EB)",
  })),
  ...[
    "Bank of America Business Advantage Secured",
    "Bank of America Business Advantage Secured Credit Line",
    "First National Bank Business Edition Secured Mastercard",
    "Valley Visa Secured Business Credit Card",
  ].map((name, index) => ({
    name,
    group: "Secured business credit cards",
    type: "Secured card / secured line",
    requirements: ["Business bank account", "Deposit available", "Identity consistency"],
    recommended: ["Domain email", "90+ days", "Clean bank profile"],
    fixKeys: ["bank", "address", "phones"],
    timing: "Use when a deposit-backed bridge is safer than unsecured applications.",
    why: "Secured cards can fit earlier if the business profile is consistent and cash deposit is available.",
    applyHref: "/starter-cards/",
    gradient: index % 2 ? "linear-gradient(135deg,#0E1A2B,#64748B)" : "linear-gradient(135deg,#0E1A2B,#15803D)",
  })),
  ...[
    "Capital One Spark Classic for Business",
    "Capital One Spark Cash Select",
    "Chase Ink Business Cash",
    "Chase Ink Business Unlimited",
    "American Express Blue Business Cash",
    "American Express Business Gold",
    "U.S. Bank Business Triple Cash Rewards",
    "Wells Fargo Signify Business Cash",
    "CitiBusiness AAdvantage",
    "Capital on Tap Business Credit Card",
  ].map((name, index) => ({
    name,
    group: "Traditional business credit cards",
    type: "Business credit card",
    requirements: ["Business bank account", "Bank rating", "Readiness criteria", "Clean identity signals"],
    recommended: ["Net 30 history", "Good owner credit", "90+ days in records"],
    fixKeys: ["bank", "bank-rating", "criteria", "phones", "address"],
    timing: "Use only after profile, bank, and criteria checks are strong enough for review.",
    why: "Traditional cards are better saved until the business can support underwriting checks.",
    applyHref: "/general-credit-cards/",
    gradient: index % 2 ? "linear-gradient(135deg,#1E1B4B,#2563EB)" : "linear-gradient(135deg,#111827,#B45309)",
  })),
  ...[
    "Ramp Card",
    "Brex Card",
    "BILL Divvy Corporate Card",
    "Rho Corporate Card",
    "Mercury IO Mastercard",
  ].map((name, index) => ({
    name,
    group: "Corporate/no-PG cards",
    type: "Corporate / no-PG review",
    requirements: ["Revenue/cash flow", "Bank activity", "Website", "Domain email", "Readiness criteria"],
    recommended: ["Operating history", "Clean identity profile"],
    fixKeys: ["bank", "website", "email", "criteria"],
    timing: "Use only when bank activity and operating signals support the platform review.",
    why: "No-PG/corporate platforms usually review cash flow and real operating presence.",
    applyHref: "/revolving-business-credit-cards/",
    gradient: index % 2 ? "linear-gradient(135deg,#020617,#334155)" : "linear-gradient(135deg,#0F172A,#0891B2)",
  })),
  ...[
    "Amazon Business American Express",
    "Sam's Club Business Mastercard",
    "Costco Anywhere Visa Business",
    "Home Depot Commercial Account",
    "Lowe's Business Advantage",
    "Dell Business Credit",
    "NeweggBusiness Net Terms",
    "Shell Small Business Card",
    "WEX Fleet Card",
    "BP Business Solutions Fuel Card",
    "Chevron Texaco Business Card",
  ].map((name, index) => ({
    name,
    group: "Store/project/fleet cards",
    type: "Store, project, or fleet card",
    requirements: ["EIN", "Address", "Bank account", "Business purpose"],
    recommended: ["Website", "Vendor history", "Bank rating"],
    fixKeys: ["ein", "address", "bank", index > 4 ? "bank-rating" : "website"],
    timing: "Use when the card supports real purchasing, project, or travel needs.",
    why: "These accounts should match the business activity and current readiness stage.",
    applyHref: "/revolving-business-credit-cards/",
    gradient: index % 2 ? "linear-gradient(135deg,#0E1A2B,#DC2626)" : "linear-gradient(135deg,#0E1A2B,#2563EB)",
  })),
  ...[
    "Bank of America Business Advantage Credit Line Cash Secured",
    "Bank of America Secured Business Loan",
    "Bank of America Secured Business Line of Credit",
    "Chase Business Line of Credit",
    "Chase SBA Express / SBA-backed line",
    "Local bank CD-secured business loan",
    "Credit union share-secured business loan",
    "SBA Lender Match",
    "SBA 7(a) loan discussion with bank",
    "SBA 504 fixed asset financing",
    "Accion Opportunity Fund",
    "CDFI / community lender search",
    "Equipment financing through current bank",
    "Bank relationship term loan",
    "Business checking relationship review",
    "Deposit-backed starter funding plan",
    "Merchant cash advance warning review",
    "Invoice factoring readiness check",
    "Business grant search as non-debt option",
    "SCORE funding mentor session",
  ].map((name, index) => ({
    name,
    group: "Funding and secured-loan paths",
    type: index < 7 ? "Secured / bank funding path" : index < 14 ? "SBA / community lender path" : "Funding advisory path",
    requirements: ["Business bank account", "Bank relationship", "Statements", "Funding purpose", "Readiness criteria"],
    recommended: ["Revenue/cash flow", "Tax returns", "Collateral or reserve", "No recent negatives"],
    fixKeys: ["bank", "bank-rating", "criteria"],
    timing: "Review after identity, banking, statements, and purpose are ready. Funding is never guaranteed.",
    why: "Funding paths require documentation and timing discipline; use this as a readiness guide, not an approval promise.",
    applyHref: "/cd-business-loans/",
    gradient: index % 2 ? "linear-gradient(135deg,#064E3B,#15803D)" : "linear-gradient(135deg,#0E1A2B,#475569)",
  })),
];

export const accountGroups = Array.from(new Set(accountCatalog.map((item) => item.group)));

export function accountStatus(item: AccountCatalogItem, openIssueKeys: Set<string>, completedKeys: Set<string>): { tone: CatalogTone; label: string; blockers: string[] } {
  const blockers = item.fixKeys.filter((key) => openIssueKeys.has(key) && !completedKeys.has(key));
  if (blockers.length) return { tone: "locked", label: "Fix first", blockers };
  if (item.group.includes("Funding") || item.group.includes("Corporate") || item.group.includes("Traditional")) return { tone: "review", label: "Guided review", blockers: [] };
  return { tone: "ready", label: "Ready to review", blockers: [] };
}

