// Official Secretary of State business-search sites (50 states + DC),
// used by the state-record picker on the sos fix page.
export const STATE_SITES: Record<string, string> = {
  "Alabama": "https://arc-sos.state.al.us/CGI/CORPNAME.MBR/INPUT",
  "Alaska": "https://www.commerce.alaska.gov/cbp/main/search/entities",
  "Arizona": "https://ecorp.azcc.gov/EntitySearch/Index",
  "Arkansas": "https://www.sos.arkansas.gov/corps/search_all.php",
  "California": "https://bizfileonline.sos.ca.gov/search/business",
  "Colorado": "https://www.coloradosos.gov/biz/BusinessEntityCriteriaExt.do",
  "Connecticut": "https://service.ct.gov/business/s/onlinebusinesssearch",
  "Delaware": "https://icis.corp.delaware.gov/Ecorp/EntitySearch/NameSearch.aspx",
  "Florida": "https://search.sunbiz.org/Inquiry/CorporationSearch/ByName",
  "Georgia": "https://ecorp.sos.ga.gov/BusinessSearch",
  "Hawaii": "https://hbe.ehawaii.gov/documents/search.html",
  "Idaho": "https://sosbiz.idaho.gov/search/business",
  "Illinois": "https://apps.ilsos.gov/businessentitysearch/",
  "Indiana": "https://bsd.sos.in.gov/publicbusinesssearch",
  "Iowa": "https://sos.iowa.gov/search/business/search.aspx",
  "Kansas": "https://www.sos.ks.gov/eforms/BusinessEntity/Search.aspx",
  "Kentucky": "https://web.sos.ky.gov/ftshow/(S())/default.aspx",
  "Louisiana": "https://coraweb.sos.la.gov/CommercialSearch/CommercialSearch.aspx",
  "Maine": "https://icrs.informe.org/nei-sos-icrs/ICRS",
  "Maryland": "https://egov.maryland.gov/businessexpress/entitysearch",
  "Massachusetts": "https://corp.sec.state.ma.us/CorpWeb/CorpSearch/CorpSearch.aspx",
  "Michigan": "https://cofs.lara.state.mi.us/SearchApi/Search/Search",
  "Minnesota": "https://mblsportal.sos.state.mn.us/Business/Search",
  "Mississippi": "https://corp.sos.ms.gov/corp/portal/c/page/corpBusinessIdSearch/portal.aspx",
  "Missouri": "https://bsd.sos.mo.gov/search/business/businesssearch.aspx",
  "Montana": "https://biz.sosmt.gov/search/business",
  "Nebraska": "https://www.nebraska.gov/sos/corp/corpsearch.cgi",
  "Nevada": "https://esos.nv.gov/EntitySearch/OnlineEntitySearch",
  "New Hampshire": "https://quickstart.sos.nh.gov/online/BusinessInquire",
  "New Jersey": "https://www.njportal.com/DOR/BusinessNameSearch/Search/BusinessName",
  "New Mexico": "https://enterprise.sos.nm.gov/search",
  "New York": "https://apps.dos.ny.gov/publicInquiry/",
  "North Carolina": "https://www.sosnc.gov/online_services/search/by_title/_Business_Registration",
  "North Dakota": "https://firststop.sos.nd.gov/search/business",
  "Ohio": "https://businesssearch.ohiosos.gov/",
  "Oklahoma": "https://www.sos.ok.gov/corp/corpInquiryFind.aspx",
  "Oregon": "https://sos.oregon.gov/business/Pages/find.aspx",
  "Pennsylvania": "https://file.dos.pa.gov/search/business",
  "Rhode Island": "https://business.sos.ri.gov/CorpWeb/CorpSearch/CorpSearch.aspx",
  "South Carolina": "https://businessfilings.sc.gov/BusinessFiling/Entity/Search",
  "South Dakota": "https://sosenterprise.sd.gov/BusinessServices/Business/FilingSearch.aspx",
  "Tennessee": "https://tncab.tnsos.gov/business-entity-search",
  "Texas": "https://www.sos.state.tx.us/corp/sosda/index.shtml",
  "Utah": "https://secure.utah.gov/bes/",
  "Vermont": "https://bizfilings.vermont.gov/online/BusinessInquire",
  "Virginia": "https://cis.scc.virginia.gov/EntitySearch/Index",
  "Washington": "https://ccfs.sos.wa.gov/#/",
  "West Virginia": "https://apps.sos.wv.gov/business/corporations/",
  "Wisconsin": "https://www.wdfi.org/apps/CorpSearch/Search.aspx",
  "Wyoming": "https://wyobiz.wyo.gov/Business/FilingSearch.aspx",
  "District of Columbia": "https://corponline.dcra.dc.gov/Home.aspx/Landing",
};
